<a href="https://colab.research.google.com/github/NelsonPixels/TensorFlow/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zerod = tf.constant(4)
print(tensor_zerod)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_oned = tf.constant([2,0,-3,5], dtype=tf.float16)
casted_oned = tf.cast(tensor_oned,dtype=tf.int16)
print(tensor_oned)
print(casted_oned)

tf.Tensor([ 2.  0. -3.  5.], shape=(4,), dtype=float16)
tf.Tensor([ 2  0 -3  5], shape=(4,), dtype=int16)


In [ ]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_twod = tf.constant([
    [2,4,5],
    [3,5,6],
    [7,8,2],
    [2,4,5]
])
print(tensor_twod)

tf.Tensor(
[[2 4 5]
 [3 5 6]
 [7 8 2]
 [2 4 5]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_string = tf.constant(["Hello world","Day"])
print(tensor_string)

tf.Tensor([b'Hello world' b'Day'], shape=(2,), dtype=string)


In [ ]:
tensor_threed = tf.constant([
    [
        [1,2,3],
        [2,3,5]
    ],
    [
        [5,4,7],
        [3,6,7]
    ],
    [
        [7,8,7],
        [5,6,9]
    ]
])

print(tensor_threed)
# print shape - print(tensor_threed.shape)
# number of dimension - print(tensor_threed.ndim)

tf.Tensor(
[[[1 2 3]
  [2 3 5]]

 [[5 4 7]
  [3 6 7]]

 [[7 8 7]
  [5 6 9]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
tensor_fourd = tf.constant([
    [
    [
        [1,2,3],
        [2,3,5]
    ],
    [
        [5,4,7],
        [3,6,7]
    ],
    [
        [7,8,7],
        [5,6,9]
    ]
],
    [
    [
        [1,2,3],
        [2,3,5]
    ],
    [
        [5,4,7],
        [3,6,7]
    ],
    [
        [7,8,7],
        [5,6,9]
    ]
]
])
print(tensor_fourd)

tf.Tensor(
[[[[1 2 3]
   [2 3 5]]

  [[5 4 7]
   [3 6 7]]

  [[7 8 7]
   [5 6 9]]]


 [[[1 2 3]
   [2 3 5]]

  [[5 4 7]
   [3 6 7]]

  [[7 8 7]
   [5 6 9]]]], shape=(2, 3, 2, 3), dtype=int32)


In [30]:
import numpy as np

In [32]:
np_array = np.array([1,3,5])
print(np_array)

[1 3 5]


In [34]:
convert_tensor = tf.convert_to_tensor(np_array)
print(convert_tensor)

tf.Tensor([1 3 5], shape=(3,), dtype=int64)


In [37]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(4*eye_tensor)

tf.Tensor(
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]], shape=(3, 3), dtype=float32)
