<a href="https://colab.research.google.com/github/NelsonPixels/TensorFlow-CheatSheet/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zerod = tf.constant(4)
print(tensor_zerod)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_oned = tf.constant([2,0,-3,5], dtype=tf.float16)
casted_oned = tf.cast(tensor_oned,dtype=tf.int16)
print(tensor_oned)
print(casted_oned)

tf.Tensor([ 2.  0. -3.  5.], shape=(4,), dtype=float16)
tf.Tensor([ 2  0 -3  5], shape=(4,), dtype=int16)


In [ ]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_twod = tf.constant([
    [2,4,5],
    [3,5,6],
    [7,8,2],
    [2,4,5]
])
print(tensor_twod)

tf.Tensor(
[[2 4 5]
 [3 5 6]
 [7 8 2]
 [2 4 5]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_string = tf.constant(["Hello world","Day"])
print(tensor_string)

tf.Tensor([b'Hello world' b'Day'], shape=(2,), dtype=string)


In [ ]:
tensor_threed = tf.constant([
    [
        [1,2,3],
        [2,3,5]
    ],
    [
        [5,4,7],
        [3,6,7]
    ],
    [
        [7,8,7],
        [5,6,9]
    ]
])

print(tensor_threed)
# print shape - print(tensor_threed.shape)
# number of dimension - print(tensor_threed.ndim)

tf.Tensor(
[[[1 2 3]
  [2 3 5]]

 [[5 4 7]
  [3 6 7]]

 [[7 8 7]
  [5 6 9]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
tensor_fourd = tf.constant([
    [
    [
        [1,2,3],
        [2,3,5]
    ],
    [
        [5,4,7],
        [3,6,7]
    ],
    [
        [7,8,7],
        [5,6,9]
    ]
],
    [
    [
        [1,2,3],
        [2,3,5]
    ],
    [
        [5,4,7],
        [3,6,7]
    ],
    [
        [7,8,7],
        [5,6,9]
    ]
]
])
print(tensor_fourd)

tf.Tensor(
[[[[1 2 3]
   [2 3 5]]

  [[5 4 7]
   [3 6 7]]

  [[7 8 7]
   [5 6 9]]]


 [[[1 2 3]
   [2 3 5]]

  [[5 4 7]
   [3 6 7]]

  [[7 8 7]
   [5 6 9]]]], shape=(2, 3, 2, 3), dtype=int32)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,3,5])
print(np_array)

[1 3 5]


In [ ]:
convert_tensor = tf.convert_to_tensor(np_array)
print(convert_tensor)

tf.Tensor([1 3 5], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns=3,
    batch_shape=[2,],
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[ True False False]
  [False  True False]
  [False False  True]
  [False False False]]

 [[ True False False]
  [False  True False]
  [False False  True]
  [False False False]]], shape=(2, 4, 3), dtype=bool)


In [ ]:
fill_tensor = tf.fill(
    [2,3,2],5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5]
  [5 5]
  [5 5]]

 [[5 5]
  [5 5]
  [5 5]]], shape=(2, 3, 2), dtype=int32)


In [ ]:
ones_tensor = tf.ones(
    [2,5,6],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]], shape=(2, 5, 6), dtype=float32)


In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean=10.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 9.397194   7.695371 ]
 [ 9.52965   10.379027 ]
 [11.522743   7.9417777]], shape=(3, 2), dtype=float32)


In [ ]:
rando_tensor = tf.random.uniform(
    [3,],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(rando_tensor)

tf.Tensor([80 31 96], shape=(3,), dtype=int32)


Indexing

In [ ]:
tensor_indexed = tf.constant([5,3,6,7,4,5,2])
print(tensor_indexed)

tf.Tensor([5 3 6 7 4 5 2], shape=(7,), dtype=int32)


In [ ]:
# Get the first two columns
tensor_twod = tf.constant([
    [4,5,5],
    [1,7,3],
    [3,5,1],
    [2,6,6]
])
print(tensor_twod[0:3,0:2])

tf.Tensor(
[[4 5]
 [1 7]
 [3 5]], shape=(3, 2), dtype=int32)


Math Operations

In [ ]:
x_abs = tf.constant([3,5])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [ ]:
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [ ]:
tf.sqrt((-3.2)**2 + 4**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.1224995>

In [ ]:
a = tf.constant([2,4,6,5,8], dtype=tf.int32)
b = tf.constant([8,6,2,4,6], dtype=tf.int32)
print(tf.math.add(a,b))
print(tf.multiply(a,b))

tf.Tensor([10 10  8  9 14], shape=(5,), dtype=int32)
tf.Tensor([16 24 12 20 48], shape=(5,), dtype=int32)


In [ ]:
x_arg = tf.constant([21,54,87,45,12])
print(tf.math.argmax(x_arg))

tf.Tensor(2, shape=(), dtype=int64)


In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[2, 1], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  2],
       [ 9, 27]], dtype=int32)>

In [ ]:
tf.pow(tf.constant(3),tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=27>

In [ ]:
tensor_twod = tf.constant([
    [2,4,3],
    [3,4,7],
    [5,-2,3],
    [2,4,9]
])
print(tensor_twod)
print(tf.math.reduce_max(tensor_twod, axis=None, keepdims=False, name=None))
print(tf.math.reduce_sum(tensor_twod, axis=0, keepdims=False, name=None))

tf.Tensor(
[[ 2  4  3]
 [ 3  4  7]
 [ 5 -2  3]
 [ 2  4  9]], shape=(4, 3), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([12 10 22], shape=(3,), dtype=int32)


In [94]:
tf.math.top_k(tensor_twod, k = 2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [7, 4],
       [5, 3],
       [9, 4]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 1],
       [0, 2],
       [2, 1]], dtype=int32)>)