<a href="https://colab.research.google.com/github/NelsonPixels/TensorFlow/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf

In [7]:
tensor_zerod = tf.constant(4)
print(tensor_zerod)

tf.Tensor(4, shape=(), dtype=int32)


In [11]:
tensor_oned = tf.constant([2,0,-3,5])
print(tensor_oned)

tf.Tensor([ 2  0 -3  5], shape=(4,), dtype=int32)


In [16]:
tensor_twod = tf.constant([
    [2,4,5],
    [3,5,6],
    [7,8,2],
    [2,4,5]
])
print(tensor_twod)

tf.Tensor(
[[2 4 5]
 [3 5 6]
 [7 8 2]
 [2 4 5]], shape=(4, 3), dtype=int32)


In [19]:
tensor_threed = tf.constant([
    [
        [1,2,3],
        [2,3,5]
    ],
    [
        [5,4,7],
        [3,6,7]
    ],
    [
        [7,8,7],
        [5,6,9]
    ]
])

print(tensor_threed)

tf.Tensor(
[[[1 2 3]
  [2 3 5]]

 [[5 4 7]
  [3 6 7]]

 [[7 8 7]
  [5 6 9]]], shape=(3, 2, 3), dtype=int32)
