<a href="https://colab.research.google.com/github/NelsonPixels/TensorFlow-CheatSheet/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tensor_zerod = tf.constant(4)
print(tensor_zerod)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_oned = tf.constant([2,0,-3,5], dtype=tf.float16)
casted_oned = tf.cast(tensor_oned,dtype=tf.int16)
print(tensor_oned)
print(casted_oned)

tf.Tensor([ 2.  0. -3.  5.], shape=(4,), dtype=float16)
tf.Tensor([ 2  0 -3  5], shape=(4,), dtype=int16)


In [ ]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_twod = tf.constant([
    [2,4,5],
    [3,5,6],
    [7,8,2],
    [2,4,5]
])
print(tensor_twod)

tf.Tensor(
[[2 4 5]
 [3 5 6]
 [7 8 2]
 [2 4 5]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_string = tf.constant(["Hello world","Day"])
print(tensor_string)

tf.Tensor([b'Hello world' b'Day'], shape=(2,), dtype=string)


In [ ]:
tensor_threed = tf.constant([
    [
        [1,2,3],
        [2,3,5]
    ],
    [
        [5,4,7],
        [3,6,7]
    ],
    [
        [7,8,7],
        [5,6,9]
    ]
])

print(tensor_threed)
# print shape - print(tensor_threed.shape)
# number of dimension - print(tensor_threed.ndim)

tf.Tensor(
[[[1 2 3]
  [2 3 5]]

 [[5 4 7]
  [3 6 7]]

 [[7 8 7]
  [5 6 9]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
 tensor_fourd = tf.constant([
    [
    [
        [1,2,3],
        [2,3,5]
    ],
    [
        [5,4,7],
        [3,6,7]
    ],
    [
        [7,8,7],
        [5,6,9]
    ]
],
    [
    [
        [1,2,3],
        [2,3,5]
    ],
    [
        [5,4,7],
        [3,6,7]
    ],
    [
        [7,8,7],
        [5,6,9]
    ]
]
])
print(tensor_fourd)

tf.Tensor(
[[[[1 2 3]
   [2 3 5]]

  [[5 4 7]
   [3 6 7]]

  [[7 8 7]
   [5 6 9]]]


 [[[1 2 3]
   [2 3 5]]

  [[5 4 7]
   [3 6 7]]

  [[7 8 7]
   [5 6 9]]]], shape=(2, 3, 2, 3), dtype=int32)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,3,5])
print(np_array)

[1 3 5]


In [ ]:
convert_tensor = tf.convert_to_tensor(np_array)
print(convert_tensor)

tf.Tensor([1 3 5], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns=3,
    batch_shape=[2,],
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[ True False False]
  [False  True False]
  [False False  True]
  [False False False]]

 [[ True False False]
  [False  True False]
  [False False  True]
  [False False False]]], shape=(2, 4, 3), dtype=bool)


In [ ]:
fill_tensor = tf.fill(
    [2,3,2],5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5]
  [5 5]
  [5 5]]

 [[5 5]
  [5 5]
  [5 5]]], shape=(2, 3, 2), dtype=int32)


In [ ]:
ones_tensor = tf.ones(
    [2,5,6],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]], shape=(2, 5, 6), dtype=float32)


In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean=10.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 9.397194   7.695371 ]
 [ 9.52965   10.379027 ]
 [11.522743   7.9417777]], shape=(3, 2), dtype=float32)


In [ ]:
rando_tensor = tf.random.uniform(
    [3,],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(rando_tensor)

tf.Tensor([80 31 96], shape=(3,), dtype=int32)


Indexing

In [ ]:
tensor_indexed = tf.constant([5,3,6,7,4,5,2])
print(tensor_indexed)

tf.Tensor([5 3 6 7 4 5 2], shape=(7,), dtype=int32)


In [ ]:
# Get the first two columns
tensor_twod = tf.constant([
    [4,5,5],
    [1,7,3],
    [3,5,1],
    [2,6,6]
])
print(tensor_twod[0:3,0:2])

tf.Tensor(
[[4 5]
 [1 7]
 [3 5]], shape=(3, 2), dtype=int32)


Math Operations

In [ ]:
x_abs = tf.constant([3,5])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [ ]:
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [ ]:
tf.sqrt((-3.2)**2 + 4**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.1224995>

In [ ]:
a = tf.constant([2,4,6,5,8], dtype=tf.int32)
b = tf.constant([8,6,2,4,6], dtype=tf.int32)
print(tf.math.add(a,b))
print(tf.multiply(a,b))

tf.Tensor([10 10  8  9 14], shape=(5,), dtype=int32)
tf.Tensor([16 24 12 20 48], shape=(5,), dtype=int32)


In [ ]:
x_arg = tf.constant([21,54,87,45,12])
print(tf.math.argmax(x_arg))

tf.Tensor(2, shape=(), dtype=int64)


In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[2, 1], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  2],
       [ 9, 27]], dtype=int32)>

In [ ]:
tf.pow(tf.constant(3),tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=27>

In [ ]:
tensor_twod = tf.constant([
    [2,4,3],
    [3,4,7],
    [5,-2,3],
    [2,4,9]
])
print(tensor_twod)
print(tf.math.reduce_max(tensor_twod, axis=None, keepdims=False, name=None))
print(tf.math.reduce_sum(tensor_twod, axis=0, keepdims=False, name=None))

tf.Tensor(
[[ 2  4  3]
 [ 3  4  7]
 [ 5 -2  3]
 [ 2  4  9]], shape=(4, 3), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([12 10 22], shape=(3,), dtype=int32)


In [ ]:
tf.math.top_k(tensor_twod, k = 2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [7, 4],
       [5, 3],
       [9, 4]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 1],
       [0, 2],
       [2, 1]], dtype=int32)>)

Linear Algebra Operations

In [ ]:
a = tf.constant([
    [4,5,6],
    [4,8,6]
])
b = tf.constant([
    [3,5,2],
    [1,2,4],
    [2,3,4]
])
print(a.shape,b.shape)
tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)


(2, 3) (3, 3)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[29, 48, 52],
       [32, 54, 64]], dtype=int32)>

In [ ]:
print(a@b)
# @ matrix multiplication
# ~ element-wise multiplication

tf.Tensor(
[[29 48 52]
 [32 54 64]], shape=(2, 3), dtype=int32)


In [ ]:
tf.transpose(a)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 4],
       [5, 8],
       [6, 6]], dtype=int32)>

In [ ]:
# Copy a tensor setting everything outside a central band in each innermost matrix to zero


In [ ]:
# inverse of a matrix
tensor_inv = tf.constant([
    [2,5,3],
    [2,5,8],
    [3,4,1]
], dtype=tf.float32)
tf.linalg.inv(tensor_inv)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7714286 ,  0.20000003,  0.71428573],
       [ 0.62857145, -0.20000002, -0.2857143 ],
       [-0.2       ,  0.2       , -0.        ]], dtype=float32)>

In [ ]:
# Computes the singular value decompositions of one or more matrices
# s is a tensor of singular values.
# u is a tensor of left singular vectors.
# v is a tensor of right singular vectors.
s,u,v = tf.linalg.svd(tensor_inv)
print(s)
print(u)
print(v)

tf.Tensor([11.917906    3.7898734   0.77489656], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.5010848   0.37027884 -0.78218156]
 [ 0.7886414  -0.567524    0.23656172]
 [ 0.35631293  0.73539805  0.5763948 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.30612695  0.47803822  0.82326543]
 [ 0.66067696  0.5159452  -0.5452585 ]
 [ 0.68541414 -0.7108308   0.15788412]], shape=(3, 3), dtype=float32)


Einsum Operator

In [ ]:
A = np.array([
    [5,2,3,4],
    [4,2,1,6],
    [2,3,6,9]])
B = np.array([
    [3,1,5,6,1],
    [1,3,4,5,6],
    [3,1,4,6,5],
    [1,3,5,2,1]])
print("Matmul C =: \n")
print(np.matmul(A,B), "\n")
print("Eisum C =: \n")
print(np.einsum('ij,jk -> ik', A,B))

Matmul C =: 

[[30 26 65 66 36]
 [23 29 62 52 27]
 [36 44 91 81 59]] 

Eisum C =: 

[[30 26 65 66 36]
 [23 29 62 52 27]
 [36 44 91 81 59]]


In [ ]:
tensor_threed = tf.constant([
    [
        [1,2,3],
        [2,3,5]
    ],
    [
        [5,4,7],
        [3,6,7]
    ],
    [
        [7,8,7],
        [5,6,9]
    ]
])
print(tensor_threed.shape)
print(tf.expand_dims(tensor_threed, axis=0))

(3, 2, 3)
tf.Tensor(
[[[[1 2 3]
   [2 3 5]]

  [[5 4 7]
   [3 6 7]]

  [[7 8 7]
   [5 6 9]]]], shape=(1, 3, 2, 3), dtype=int32)


In [ ]:
x = tf.constant([[[3,2,4]]])
print(x.shape)
x_expanded = tf.expand_dims(x, axis = 0)
print(x_expanded)

(1, 1, 3)
tf.Tensor([[[[3 2 4]]]], shape=(1, 1, 1, 3), dtype=int32)


In [ ]:
x_squeezed = tf.squeeze(x_expanded, axis = 0)
for i in range(2):
  x_squeezed = tf.squeeze(x_squeezed, axis = 0)

print(x_squeezed)

tf.Tensor([3 2 4], shape=(3,), dtype=int32)


In [ ]:
# Concatenates tensors along one dimension
# axis 0 or 1
t1 = [
    [2,4,3],
    [5,6,1]]
t2 = [
    [2,1,3],
    [1,5,4]]
tf.concat([t1,t2], axis=1)


<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[2, 4, 3, 2, 1, 3],
       [5, 6, 1, 1, 5, 4]], dtype=int32)>

In [ ]:
tf.stack([t1,t2], axis=1)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[2, 4, 3],
        [2, 1, 3]],

       [[5, 6, 1],
        [1, 5, 4]]], dtype=int32)>

In [ ]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1,],  # one row above, one row below
                      [2, 2]])
tf.pad(t, paddings, "CONSTANT", constant_values=3)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 1, 2, 3, 3, 3],
       [3, 3, 4, 5, 6, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]], dtype=int32)>

In [ ]:
# Gather slices from params axis axis according to indices. (deprecated arguments)
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params[0:3]
tf.gather(params,tf.range(2,4))

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'p2', b'p3'], dtype=object)>

In [ ]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])

print(params.shape)

(4, 3)


In [ ]:
tf.gather(params,[2,0], axis = 0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[20., 21., 22.],
       [ 0.,  1.,  2.]], dtype=float32)>

In [ ]:
indices = [[0],
           [1]]
params = [
    ['a', 'b'],
    ['c', 'd']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'a', b'b'],
       [b'c', b'd']], dtype=object)>

In [ ]:
# ragged tensors. Tensors with non-uniform shape
tensor_td = [
    [2,3,1],
    [2],
    [4,2],
    [5,3,2,4]
]
tensor_ragged = tf.ragged.constant(tensor_td)
print(tensor_ragged)

<tf.RaggedTensor [[2, 3, 1], [2], [4, 2], [5, 3, 2, 4]]>


In [51]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
